import Head from "next/head"
const Home = () => {
    return (
        <>
            
            <Head>
                <title>Admin</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Halo Kamu sudah login</h1>
        </>
        
    )
}

export default Home;